security:
    encoders:
        App\Entity\User:
            algorithm: auto
            cost:      10
    providers:
        database:
            entity:
                class: App\Entity\User
                property: username

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPERUSER: [ROLE_USER, ROLE_ADMIN]

    firewalls:
        assets_and_debug:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_control:
            pattern: ^/
            access_denied_handler: App\Security\Handler\AccessDeniedHandler
            user_checker: App\Service\UserChecker
            provider: database
            anonymous: true
            guard:
                authenticators:
                    - App\Service\AuthenticatorService
            form_login:
                login_path: user_login
                check_path: user_login_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   user_logout
                target: homepage

    access_control:
        #todo force to https
        - { path: ^/ticket/(view/\d+|list)$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/%user_path%/ticket, roles: [IS_AUTHENTICATED_FULLY, ROLE_USER, ROLE_ADMIN], requires_channel: http }
        - { path: ^/%user_path%/(enregistrement|connexion), roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/%user_path%, roles: [IS_AUTHENTICATED_FULLY, ROLE_USER, ROLE_ADMIN], requires_channel: http }
        - { path: ^/legal/(data-protection|cgu|mentions), roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
